version: '3.4'

services:

  rmarket:
    build: .
    command: npm run start
    
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    expose:
      - 5000
    ports:
      - "5000:5000"
    
    restart: unless-stopped
